import React, { useState } from 'react';
// @ts-ignore - This will be generated by Hilla
import { MockEndpointEndpoint } from 'Frontend/generated/endpoints.js';

export default function App() {
  const [jsonPayload, setJsonPayload] = useState('{\n  "id": 1,\n  "nome": "Produto exemplo"\n}');
  const [generatedUrl, setGeneratedUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleGenerateKey = async () => {
    setLoading(true);
    try {
      const response = await MockEndpointEndpoint.create({
        payload: jsonPayload,
        statusCode: 200,
        delayMs: 0,
        label: 'Frontend Generated'
      });
      if (response && response.url) {
        setGeneratedUrl(response.url);
      } else {
        alert("Erro: Não foi possível obter a URL do servidor.");
      }
    } catch (error) {
      console.error("Falha ao criar o endpoint", error);
      alert("Falha de comunicação com o backend. O JSON é válido?");
    } finally {
      setLoading(false);
    }
  };

  const handleFormatJson = () => {
    try {
      const parsed = JSON.parse(jsonPayload);
      setJsonPayload(JSON.stringify(parsed, null, 2));
    } catch (e) {
      alert("JSON inválido para formatação.");
    }
  };

  return (
    <div className="app-container">
      <header className="navbar">
        <div className="logo-container">
          <div className="logo-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <rect width="24" height="24" rx="6" fill="#4B77FE" />
              <path d="M7 10h10M7 14h6" stroke="white" strokeWidth="2" strokeLinecap="round" />
              <circle cx="15.5" cy="14.5" r="2.5" fill="white" />
            </svg>
          </div>
          <span className="logo-text">res<span className="logo-text-highlight">test</span></span>
        </div>
        <nav className="nav-links">
          <a href="#">docs</a>
          <a href="#">exemplos</a>
          <a href="#">pricing</a>
          <span className="beta-badge">beta</span>
        </nav>
      </header>

      <main className="main-content">
        <div className="hero-section">
          <div className="pill-badge">
            <span className="blue-dot"></span> ferramenta para devs frontend
          </div>
          <h1 className="hero-title">Teste suas APIs REST com <span className="highlight-text">seus próprios JSONs</span></h1>
          <p className="hero-subtitle">
            Cole seu JSON, gere uma chave de API e consuma via endpoint REST. Sem configuração, sem backend. Pronto para usar em segundos.
          </p>
        </div>

        <div className="editor-section">
          <div className="editor-header-outer">
            <div className="editor-title">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path></svg>
              <span>payload json</span>
            </div>
            <div className="http-methods">
              <button className="method-btn active">GET</button>
              <button className="method-btn">POST</button>
              <button className="method-btn">PUT</button>
              <button className="method-btn">DELETE</button>
            </div>
          </div>

          <div className="editor-window">
            <div className="editor-window-header">
              <div className="mac-dots">
                <span className="dot red"></span>
                <span className="dot yellow"></span>
                <span className="dot green"></span>
              </div>
              <span className="filename">json-payload.json</span>
            </div>
            <div className="editor-body">
              <textarea
                className="code-textarea"
                value={jsonPayload}
                onChange={(e) => setJsonPayload(e.target.value)}
                spellCheck="false"
              />
            </div>
          </div>

          {generatedUrl && (
            <div className="generated-url-container">
              <p>Sua URL pronta para uso:</p>
              <div className="url-box">
                <input type="text" readOnly value={generatedUrl} />
                <button onClick={() => navigator.clipboard.writeText(generatedUrl)}>Copiar</button>
              </div>
            </div>
          )}

          <div className="action-buttons">
            <button className="action-btn primary" onClick={handleGenerateKey} disabled={loading}>
              {loading ? 'Gerando...' : 'Gerar chave API'}
            </button>
            <button className="action-btn secondary" onClick={handleFormatJson}>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="16 18 22 12 16 6"></polyline><polyline points="8 6 2 12 8 18"></polyline></svg>
              Formatar JSON
            </button>
          </div>
        </div>

        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon">⚡</div>
            <h3>Instantâneo</h3>
            <p>Endpoint pronto em menos de 1 segundo</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">🔒</div>
            <h3>Autenticado</h3>
            <p>API key exclusiva por sessão</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">🔌</div>
            <h3>Plug & play</h3>
            <p>Zero configuração de backend</p>
          </div>
        </div>
      </main>

      <footer className="footer">
        <span>© 2026 restest — made for devs</span>
        <div className="status-indicator">
          <span className="green-dot"></span> todos os serviços online
        </div>
      </footer>
    </div>
  );
}
