spring.application.name=ResTesT

spring.datasource.url=jdbc:postgresql://db.arjunftseqpimkhuhmhb.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ResTest@1233
server.port=${PORT:8080}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
